"""core.compositor.watermark — 视频水印处理器

使用 moviepy TextClip 生成水印 PNG 图片后，通过 ffmpeg overlay 滤镜叠加。
避免 moviepy CompositeVideoClip 重编码整个视频导致 OOM。
"""

import logging
import os
import re
import subprocess
import tempfile

from core.config import resolve_font_path

logger = logging.getLogger(__name__)

_CJK_RE = re.compile(r'[\u4e00-\u9fff\u3400-\u4dbf\uf900-\ufaff]')

WATERMARK_TEXTS = {
    "zh": {
        "line1": "由 Agnes Video Generator 生成",
        "line2": "video.lichuanyang.top",
    },
    "en": {
        "line1": "Generated by Agnes Video Generator",
        "line2": "video.lichuanyang.top",
    },
}


def _compute_font_size(video_height: int) -> int:
    return max(12, round(video_height * 0.022))


def detect_language(text: str) -> str:
    if not text:
        return "en"
    if _CJK_RE.search(text):
        return "zh"
    return "en"


def _build_watermark_text(language: str) -> str:
    texts = WATERMARK_TEXTS.get(language, WATERMARK_TEXTS["en"])
    return f"{texts['line1']}\n{texts['line2']}"


def _get_video_dimensions(input_path: str) -> tuple:
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_streams", input_path],
            capture_output=True, text=True, timeout=30,
        )
        info = __import__('json').loads(result.stdout)
        for s in info.get("streams", []):
            if s.get("codec_type") == "video":
                return s["width"], s["height"]
    except Exception:
        pass
    return None, None


def _render_watermark_png(
    output_png: str,
    video_width: int,
    video_height: int,
    language: str = "en",
    font_path: str = None,
) -> bool:
    """用 moviepy TextClip 渲染水印为 PNG 图片（仅一帧，内存极低）。"""
    from moviepy import TextClip

    if font_path is None:
        font_path = resolve_font_path("STHeitiMedium.ttc")
    if not os.path.exists(font_path):
        return False

    font_size = _compute_font_size(video_height)
    url_font_size = max(10, round(font_size * 0.85))
    right_margin = max(16, round(video_width * 0.02))
    bottom_margin = max(100, round(video_height * 0.12))
    line_spacing = max(2, round(font_size * 0.15))
    box_padding = max(4, round(font_size * 0.35))

    brand_blue_rgb = (30, 64, 175)

    text = _build_watermark_text(language)
    lines = text.split("\n")
    line1_text = lines[0] if len(lines) > 0 else ""
    line2_text = lines[1] if len(lines) > 1 else ""

    try:
        t1 = TextClip(text=line1_text, font=font_path, font_size=font_size,
                       color="white", stroke_color="black", stroke_width=1)
        t2 = TextClip(text=line2_text, font=font_path, font_size=url_font_size,
                       color="white", stroke_color="black", stroke_width=1)

        cw1, ch1 = t1.size if t1.size else (0, 0)
        cw2, ch2 = t2.size if t2.size else (0, 0)
        box_w = int(max(cw1, cw2) + box_padding * 2)
        box_h = int(ch1 + ch2 + line_spacing + box_padding * 2)

        pos_x = video_width - box_w - right_margin
        pos_y = video_height - box_h - bottom_margin

        from moviepy import ColorClip
        bg = ColorClip(size=(box_w, box_h), color=brand_blue_rgb).with_opacity(0.30)

        from moviepy import CompositeVideoClip
        composite = CompositeVideoClip([
            bg.with_duration(1),
            t1.with_position((box_padding, box_padding)).with_duration(1),
            t2.with_position((box_padding, box_padding + ch1 + line_spacing)).with_duration(1),
        ], size=(box_w, box_h))

        composite.save_frame(output_png, t=0)

        # 返回相对于视频的位置信息
        setattr(_render_watermark_png, '_wm_pos_x', pos_x)
        setattr(_render_watermark_png, '_wm_pos_y', pos_y)
        setattr(_render_watermark_png, '_wm_box_w', box_w)
        setattr(_render_watermark_png, '_wm_box_h', box_h)
        return True
    except Exception as e:
        logger.error(f"[Watermark] Render PNG failed: {e}")
        return False


def add_watermark(
    input_path: str,
    output_path: str,
    video_width: int = None,
    video_height: int = None,
    language: str = "en",
    font_path: str = None,
) -> bool:
    """使用 ffmpeg overlay 滤镜在视频右下角叠加水印。

    先生成水印 PNG（moviepy TextClip，一帧而已），
    再用 ffmpeg overlay 滤镜流式合成，不加载全视频到内存。
    """
    if not os.path.exists(input_path):
        logger.error(f"[Watermark] Input not found: {input_path}")
        return False

    if video_width is None or video_height is None:
        vw, vh = _get_video_dimensions(input_path)
        if vw is None or vh is None:
            logger.error(f"[Watermark] Cannot detect video dimensions: {input_path}")
            import shutil
            shutil.copy2(input_path, output_path)
            return False
        video_width, video_height = vw, vh

    if font_path is None:
        font_path = resolve_font_path("STHeitiMedium.ttc")
    if not os.path.exists(font_path):
        logger.warning(f"[Watermark] Font not found: {font_path}, copying original")
        import shutil
        shutil.copy2(input_path, output_path)
        return False

    logger.info(f"[Watermark] Processing {os.path.basename(input_path)} "
                f"({video_width}x{video_height}, lang={language}) via ffmpeg overlay")

    # 生成水印 PNG（内存友好 — 仅一帧）
    wm_png_fd, wm_png_path = tempfile.mkstemp(suffix=".png", prefix="watermark_")
    os.close(wm_png_fd)
    try:
        if not _render_watermark_png(wm_png_path, video_width, video_height, language, font_path):
            logger.error("[Watermark] Failed to render watermark PNG, copying original")
            import shutil
            shutil.copy2(input_path, output_path)
            return False

        pos_x = getattr(_render_watermark_png, '_wm_pos_x', 0)
        pos_y = getattr(_render_watermark_png, '_wm_pos_y', 0)

        # ffmpeg overlay: 将水印 PNG 叠加到视频上，无损流式拷贝
        cmd = [
            "ffmpeg", "-y",
            "-i", input_path,
            "-i", wm_png_path,
            "-filter_complex", f"[0:v][1:v]overlay={pos_x}:{pos_y}[v]",
            "-map", "[v]",
            "-map", "0:a?",  # 保留原音频
            "-c:v", "libx264", "-crf", "18", "-preset", "fast",
            "-c:a", "copy",
            output_path,
        ]

        logger.debug(f"[Watermark] ffmpeg cmd: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

        if result.returncode != 0:
            logger.error(f"[Watermark] ffmpeg failed (rc={result.returncode}): "
                         f"{result.stderr[:500]}")
            import shutil
            shutil.copy2(input_path, output_path)
            return False

        logger.info(f"[Watermark] Complete: {os.path.basename(output_path)}")
        return True

    except subprocess.TimeoutExpired:
        logger.error("[Watermark] ffmpeg timed out")
        import shutil
        shutil.copy2(input_path, output_path)
        return False
    except Exception as e:
        logger.error(f"[Watermark] Failed: {e}")
        import shutil
        shutil.copy2(input_path, output_path)
        return False
    finally:
        if os.path.exists(wm_png_path):
            try:
                os.remove(wm_png_path)
            except OSError:
                pass
